package com.example.demo.agenerate;

import lombok.Data;

@Data
public class Company2 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company2.id
     *
     * @mbg.generated Sat Oct 17 16:15:43 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company2.name
     *
     * @mbg.generated Sat Oct 17 16:15:43 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company2.age
     *
     * @mbg.generated Sat Oct 17 16:15:43 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company2.address
     *
     * @mbg.generated Sat Oct 17 16:15:43 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company2.salary
     *
     * @mbg.generated Sat Oct 17 16:15:43 CST 2020
     */
    private Float salary;
}