package com.example.demo.agenerate;

import com.example.demo.agenerate.Company2;

public interface Company2Dao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company2
     *
     * @mbg.generated Sat Oct 17 16:15:43 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company2
     *
     * @mbg.generated Sat Oct 17 16:15:43 CST 2020
     */
    int insert(Company2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company2
     *
     * @mbg.generated Sat Oct 17 16:15:43 CST 2020
     */
    int insertSelective(Company2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company2
     *
     * @mbg.generated Sat Oct 17 16:15:43 CST 2020
     */
    Company2 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company2
     *
     * @mbg.generated Sat Oct 17 16:15:43 CST 2020
     */
    int updateByPrimaryKeySelective(Company2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company2
     *
     * @mbg.generated Sat Oct 17 16:15:43 CST 2020
     */
    int updateByPrimaryKey(Company2 record);
}