package com.example.demo.entity;

import lombok.Data;

@Data
public class company2 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company2.id
     *
     * @mbggenerated Sun Oct 11 17:13:31 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company2.name
     *
     * @mbggenerated Sun Oct 11 17:13:31 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company2.age
     *
     * @mbggenerated Sun Oct 11 17:13:31 CST 2020
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company2.address
     *
     * @mbggenerated Sun Oct 11 17:13:31 CST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company2.salary
     *
     * @mbggenerated Sun Oct 11 17:13:31 CST 2020
     */
    private Float salary;
}