package com.example.demo.dao;

import com.example.demo.entity.company2;
import com.example.demo.entity.company2Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface company2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company2
     *
     * @mbggenerated Sun Oct 11 17:13:31 CST 2020
     */
    int countByExample(company2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company2
     *
     * @mbggenerated Sun Oct 11 17:13:31 CST 2020
     */
    int deleteByExample(company2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company2
     *
     * @mbggenerated Sun Oct 11 17:13:31 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company2
     *
     * @mbggenerated Sun Oct 11 17:13:31 CST 2020
     */
    int insert(company2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company2
     *
     * @mbggenerated Sun Oct 11 17:13:31 CST 2020
     */
    int insertSelective(company2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company2
     *
     * @mbggenerated Sun Oct 11 17:13:31 CST 2020
     */
    List<company2> selectByExample(company2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company2
     *
     * @mbggenerated Sun Oct 11 17:13:31 CST 2020
     */
    company2 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company2
     *
     * @mbggenerated Sun Oct 11 17:13:31 CST 2020
     */
    int updateByExampleSelective(@Param("record") company2 record, @Param("example") company2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company2
     *
     * @mbggenerated Sun Oct 11 17:13:31 CST 2020
     */
    int updateByExample(@Param("record") company2 record, @Param("example") company2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company2
     *
     * @mbggenerated Sun Oct 11 17:13:31 CST 2020
     */
    int updateByPrimaryKeySelective(company2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company2
     *
     * @mbggenerated Sun Oct 11 17:13:31 CST 2020
     */
    int updateByPrimaryKey(company2 record);
}